name: First workflow

on:
  workflow_dispatch:
    
  push:
    branches: 
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show system info
        run: uname -a

      - name: Show current date
        run: date
        
      - name: Say hello
        run: echo "Hello, world!"

      - name: Runner environment variables
        run: printenv

  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files
        run: ls -la