name: First workflow

on:
  workflow_dispatch:
    
  push:
    branches: 
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show system info
        run: uname -a

      - name: Show current date
        run: date
        
      - name: Say hello
        run: echo "Hello, world!"
