name: First workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      message:
        description: 'Custom message to display'
        required: false
        default: 'Hello from workflow dispatch!'
        type: string
      enable_logging:
        description: 'Enable verbose logging'
        required: false
        default: false
        type: boolean
    
  push:
    branches: 
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show system info
        run: uname -a

      - name: Show current date
        run: date
        
      - name: Say hello
        run: echo "Hello, world!"

      - name: Runner environment variables
        run: printenv
        
      - name: Display workflow inputs
        run: |
          echo "Environment: ${{ inputs.environment }}"

  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List files
        run: ls -la

  input-demo:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Display workflow inputs
        run: |
          echo "Environment: ${{ inputs.environment }}"
          echo "Custom message: ${{ inputs.message }}"
          echo "Enable logging: ${{ inputs.enable_logging }}"
          
      - name: Conditional logging
        if: inputs.enable_logging == true
        run: |
          echo "Verbose logging is enabled!"
          echo "Current working directory: $(pwd)"
          echo "Available disk space:"
          df -h
          
      - name: Environment-specific actions
        run: |
          if [ "${{ inputs.environment }}" = "production" ]; then
            echo "Running production deployment steps..."
            echo "⚠️ This is production - be careful!"
          else
            echo "Running staging deployment steps..."
            echo "✅ Safe to test in staging"
          fi